### ISSUE TITLE
Jobserver doesn't return ERROR OR FAILED status after NoClassDefFoundError causes 

### ISSUE THREAD

**Issue by Vern1erCa11per** [spark-jobserver/spark-jobserver#757]
I run a job on the job server which is build with the spark-2.0-preview branch.

While running it, NoClassFoundError caused 
because my way to compile the job wasn't correct.

However, the Status keeps being "Running" and didn't return the error or failed status
through GET /JOB/<jobId>API.
(even if after restart)

log is below

=============================
 [akka://JobServer/user/context-supervisor/faf6b8c0-MyClass] - Got Throwable
java.lang.NoClassDefFoundError: MyClass$
        at MyClass$.runJob(SparkSQLJob.scala:27)
        at MyClass$.runJob(SparkSQLJob.scala:22)
        at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:290)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: MyClass$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
[2017-02-28 15:04:15,237] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [spark.jobserver.JobInfoActor$JobConfigStored$] from Actor[akka://JobServer/user/job-info#-1769679544] to Actor[akka://JobServer/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2017-02-28 15:04:35,990] INFO  rk.jobserver.BinaryManager [] [akka://JobServer/user/binary-manager] - Storing binary of type Jar for app test_data_frame3, 8298 bytes
[2017-02-28 15:04:36,247] INFO  ocalContextSupervisorActor [] [akka://JobServer/user/context-supervisor] - Creating SparkContext for adhoc jobs.
[2017-02-28 15:04:36,247] INFO  ocalContextSupervisorActor [] [akka://JobServer/user/context-supervisor] - Creating a SparkContext named e8228d0e-MyClass
[2017-02-28 15:04:36,248] INFO  .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/e8228d0e-MyClass] - Starting actor spark.jobserver.JobManagerActor
[2017-02-28 15:04:36,248] INFO  k.jobserver.JobStatusActor [] [akka://JobServer/user/context-supervisor/e8228d0e-MyClass/$a] - Starting actor spark.jobserver.JobStatusActor
[2017-02-28 15:04:36,251] WARN  org.apache.spark.SparkConf [] [akka://JobServer/user/context-supervisor/e8228d0e-MyClass] - The configuration key spark.akka.threads is not supported any more because Spark doesn't use Akka since 2.0
[2017-02-28 15:04:36,252] WARN  .apache.spark.SparkContext [] [akka://JobServer/user/context-supervisor/e8228d0e-MyClass] - Multiple running SparkContexts detected in the same JVM!
org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.SparkContext.<init>(SparkContext.scala:76)
spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:119)
spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:119)
spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:114)
spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:63)
spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:114)
spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:135)
scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
akka.actor.Actor$class.aroundReceive(Actor.scala:484)
spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)

**Comment by htch** [comment]
Is it known if this bug occurs only with specific type of exceptions or all of them? I have witnessed the same behaviour with `java.lang.OutOfMemoryError`.

**Comment by bsikander** [comment]
Should be fixed in latest jobserver release.
