### PR TITLE
Upgrade to SBT-assembly 0.14 and shade shapeless jar

### PR DESCRIPTION
**Pull request by velvia**
An attempt to try out the sbt-assembly 0.14 shading function to help resolve dependency conflicts.  Right now, this shades the shapeless jar only.   I tried to shade the akka jar also, but it apparently renames some configuration values also, is too aggressive.

Also, test in assembly has to be disabled due to another bug.

### CODE REVIEW

**Comment by ravi-unifi** [comment]
Will this pull request be merged ?

**Comment by velvia** [comment]
Need to update it so that tests pass, but yes I hope so :)

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
@noorul @zeitos can you guys have a quick look and merge?   Thanks, folks asking for this and it's been sitting around for a while.

**Comment by noorul** [comment]
@velvia  Travis is not happy :(

**Comment by velvia** [comment]
Weird. Only 2.11.6 failed and only for one of them.  Passes locally.  Some stupid timing stuff.

**Comment by noorul** [comment]
Looks good to me

**Comment by noorul** [comment]
@velvia Merged :)

**Comment by velvia** [comment]
Thanks.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
All, I'm unfortunately going to have to disable the shading for the shapeless jar.  Another user reported that this causes ClassNotFound issues.  If you need it, feel free to uncomment the config in Assembly.scala and rebuild.  Sorry for any inconvenience.

**Comment by edpacheco** [comment]
Hi @velvia  (evan)

I just got into the (java.lang.NoSuchMethodError: akka.util.Helpers$.ConfigOps(Lcom/typesafe/config/Config;)Lcom/typesafe/config/Config) issue at trying to deploy SJS (master) on CDH 5.7.0.... I have not been able to  make it work with either akka's 2.3.4 or any other version... Is there any news regarding this issue? is the shading working? Is there a version of SJS that I may use with CDH 7.0? I came across with some comments reporting that using older version of SJS and downgrading other dependencies may work... does that solution work may work using CDH 5.3?

Any comments/hints will be appreciated

Thanks!

**Comment by velvia** [comment]
Yeah others can probably comment but no we haven't done the shading yet becoz shading Akka is a lot of work :(

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
