### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor;

### ISSUE THREAD

**Issue by ChenYanting** [spark-jobserver/spark-jobserver#154]
I deployed my jobserver to a folder called "jobserver". 

In jobserver folder,
>
hadoop@NN1:~/yanchen/jobserver$ ls
local.conf  log4j-server.properties  server_start.sh  server_stop.sh  settings.sh  spark-job-server.jar

Then, I tried to start the server using server_start.sh. I got the following error message.
>
hadoop@NN1:~/yanchen/jobserver$ ./server_start.sh 
hadoop@NN1:~/yanchen/jobserver$ log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.
Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor;
	at spray.routing.directives.DetachMagnet2LowerPriorityImplicits.fromImplicitRefFactory(ExecutionDirectives.scala:116)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:67)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:57)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:48)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
	at ooyala.common.akka.web.CommonRoutes$class.$init$(CommonRoutes.scala:20)
	at spark.jobserver.WebApi.<init>(WebApi.scala:22)
	at spark.jobserver.JobServer$.start(JobServer.scala:58)
	at spark.jobserver.JobServer$.main(JobServer.scala:63)
	at spark.jobserver.JobServer.main(JobServer.scala)

Do you know where might be the root cause of this exception?

In addition, I tried to execute the command using another node but got this message. 
>
hadoop@NN1:~/yanchen/spark-jobserver$ curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests_2.10-0.5.2-SNAPSHOT.jar localhost:8090/jars/test
curl: (7) couldn't connect to host

I am pretty sure that my jobserver is running now from the following command.
>
hadoop@NN1:~/yanchen/jobserver$ ps -ef | grep 999
root      1999     1  0 May18 tty1     00:00:00 /sbin/getty -8 38400 tty1
hadoop   29493     1  0 15:38 pts/1    00:00:02 java -cp /home/hadoop/yanchen/jobserver:/home/hadoop/yanchen/jobserver/spark-job-server.jar:::/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/spark/conf:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/spark/lib/spark-assembly.jar:/etc/hadoop/conf:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/client/*:/etc/hadoop/conf:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/libexec/../../hadoop/lib/*:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/libexec/../../hadoop/.//*:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/../hadoop-hdfs/./:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/../hadoop-hdfs/lib/*:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/../hadoop-hdfs/.//*:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/../hadoop-yarn/lib/*:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hadoop/../hadoop-yarn/.//*:/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/lib/*:/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/.//*:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/spark/lib/scala-library.jar:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/spark/lib/scala-compiler.jar:/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/spark/lib/jline.jar -XX:+UseConcMarkSweepGC -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:/home/hadoop/yanchen/jobserver/gc.out -XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -Xmx5g -XX:MaxDirectMemorySize=512M -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dlog4j.configuration=log4j-server.properties -DLOG_DIR=/home/hadoop/yanchen/jobserver/log -Dspark.executor.uri=/home/spark/spark-0.8.0.tar.gz spark.jobserver.JobServer /home/hadoop/yanchen/jobserver/local.conf
hadoop   29915 13994  0 15:42 pts/1    00:00:00 grep --color=auto 999

**Comment by velvia** [comment]
What exact version of Spark are you using?  (from a distro?  CDH?)

On Wed, May 20, 2015 at 12:40 AM, Yanting Chen <notifications@github.com>
wrote:

> I deployed my jobserver to a folder called "jobserver".
>
> In jobserver folder,
>
> hadoop@NN1:~/yanchen/jobserver$ ls
> local.conf log4j-server.properties server_start.sh server_stop.sh
> settings.sh spark-job-server.jar
>
> Then, I tried to start the server using server_start.sh. I got the
> following error message.
>
> hadoop@NN1:~/yanchen/jobserver$ ./server_start.sh
> hadoop@NN1:~/yanchen/jobserver$ log4j:WARN No such property [datePattern]
> in org.apache.log4j.RollingFileAppender.
> Exception in thread "main" java.lang.NoSuchMethodError:
> akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor;
> at
> spray.routing.directives.DetachMagnet2LowerPriorityImplicits.fromImplicitRefFactory(ExecutionDirectives.scala:116)
> at
> spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:67)
> at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
> at
> spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:57)
> at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
> at
> spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:48)
> at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
> at ooyala.common.akka.web.CommonRoutes$class.$init$(CommonRoutes.scala:20)
> at spark.jobserver.WebApi.(WebApi.scala:22)
> at spark.jobserver.JobServer$.start(JobServer.scala:58)
> at spark.jobserver.JobServer$.main(JobServer.scala:63)
> at spark.jobserver.JobServer.main(JobServer.scala)
>
> Do you know where might be the root cause of this exception?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/154>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ChenYanting** [comment]
@velvia  from CDH 5.3.2
Spark version is 1.2.0

**Comment by ChenYanting** [comment]
Does anyone has any idea about this error message?

**Comment by velvia** [comment]
@ChenYanting would you mind providing the class path from the Spark worker UI?   Somewhere in there we should be able to see the Akka version included in CDH 5.4..

**Comment by ChenYanting** [comment]
@velvia 

From UI
sun.boot.class.path
>
/usr/lib/jvm/java-7-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-7-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-7-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-7-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-7-oracle/jre/classes:/root/.sbt/boot/scala-2.10.4/lib/scala-library.jar:/root/.sbt/boot/scala-2.10.4/lib/scala-compiler.jar:/root/.sbt/boot/scala-2.10.4/lib/scala-reflect.jar:/root/.sbt/boot/scala-2.10.4/lib/jline.jar:/root/.sbt/boot/scala-2.10.4/lib/jansi.jar

sun.java.command
>
scala.tools.nsc.MainGenericRunner -classpath /home/hadoop/yanchen/spark-jobserver/job-server/target/scala-2.10/classes:/home/hadoop/yanchen/spark-jobserver/akka-app/target/scala-2.10/classes:/home/hadoop/yanchen/spark-jobserver/job-server-api/target/scala-2.10/classes:/root/.sbt/boot/scala-2.10.4/lib/scala-library.jar:/root/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.23.Final.jar:/root/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/root/.ivy2/cache/io.spray/spray-json_2.10/bundles/spray-json_2.10-1.3.1.jar:/root/.ivy2/cache/io.spray/spray-can_2.10/bundles/spray-can_2.10-1.3.2.jar:/root/.ivy2/cache/io.spray/spray-io_2.10/bundles/spray-io_2.10-1.3.2.jar:/root/.ivy2/cache/io.spray/spray-util_2.10/bundles/spray-util_2.10-1.3.2.jar:/root/.ivy2/cache/io.spray/spray-http_2.10/bundles/spray-http_2.10-1.3.2.jar:/root/.ivy2/cache/org.parboiled/parboiled-scala_2.10/bundles/parboiled-scala_2.10-1.1.6.jar:/root/.ivy2/cache/org.parboiled/parboiled-core/bundles/parboiled-core-1.1.6.jar:/root/.ivy2/cache/io.spray/spray-routing_2.10/bundles/spray-routing_2.10-1.3.2.jar:/root/.ivy2/cache/io.spray/spray-httpx_2.10/bundles/spray-httpx_2.10-1.3.2.jar:/root/.ivy2/cache/org.jvnet.mimepull/mimepull/jars/mimepull-1.9.4.jar:/root/.ivy2/cache/com.chuusai/shapeless_2.10/jars/shapeless_2.10-1.2.4.jar:/root/.ivy2/cache/io.spray/spray-client_2.10/bundles/spray-client_2.10-1.3.2.jar:/root/.ivy2/cache/com.yammer.metrics/metrics-core/jars/metrics-core-2.2.0.jar:/root/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.2.jar:/root/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.1.jar:/root/.ivy2/cache/com.typesafe.slick/slick_2.10/bundles/slick_2.10-2.1.0.jar:/root/.ivy2/cache/com.h2database/h2/jars/h2-1.3.170.jar:/root/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.10/jars/scalac-scoverage-runtime_2.10-1.0.4.jar:/root/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.10/jars/scalac-scoverage-plugin_2.10-1.0.4.jar:/root/.ivy2/cache/org.apache.spark/spark-core_2.10/jars/spark-core_2.10-1.3.0.jar:/root/.ivy2/cache/com.twitter/chill_2.10/jars/chill_2.10-0.5.0.jar:/root/.ivy2/cache/com.twitter/chill-java/jars/chill-java-0.5.0.jar:/root/.ivy2/cache/com.esotericsoftware.kryo/kryo/bundles/kryo-2.21.jar:/root/.ivy2/cache/com.esotericsoftware.reflectasm/reflectasm/jars/reflectasm-1.07-shaded.jar:/root/.ivy2/cache/com.esotericsoftware.minlog/minlog/jars/minlog-1.2.jar:/root/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-1.2.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-client/jars/hadoop-client-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-common/jars/hadoop-common-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-annotations/jars/hadoop-annotations-2.2.0.jar:/root/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar:/root/.ivy2/cache/commons-cli/commons-cli/jars/commons-cli-1.2.jar:/root/.ivy2/cache/org.apache.commons/commons-math/jars/commons-math-2.1.jar:/root/.ivy2/cache/xmlenc/xmlenc/jars/xmlenc-0.52.jar:/root/.ivy2/cache/commons-httpclient/commons-httpclient/jars/commons-httpclient-3.1.jar:/root/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/root/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.4.jar:/root/.ivy2/cache/log4j/log4j/bundles/log4j-1.2.17.jar:/root/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.5.jar:/root/.ivy2/cache/commons-configuration/commons-configuration/jars/commons-configuration-1.6.jar:/root/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar:/root/.ivy2/cache/commons-digester/commons-digester/jars/commons-digester-1.8.jar:/root/.ivy2/cache/commons-beanutils/commons-beanutils/jars/commons-beanutils-1.7.0.jar:/root/.ivy2/cache/commons-beanutils/commons-beanutils-core/jars/commons-beanutils-core-1.8.0.jar:/root/.ivy2/cache/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.8.8.jar:/root/.ivy2/cache/org.codehaus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.8.8.jar:/root/.ivy2/cache/org.apache.avro/avro/jars/avro-1.7.4.jar:/root/.ivy2/cache/org.apache.commons/commons-compress/jars/commons-compress-1.4.1.jar:/root/.ivy2/cache/org.tukaani/xz/jars/xz-1.0.jar:/root/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-2.5.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-auth/jars/hadoop-auth-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-hdfs/jars/hadoop-hdfs-2.2.0.jar:/root/.ivy2/cache/org.mortbay.jetty/jetty-util/jars/jetty-util-6.1.26.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-app/jars/hadoop-mapreduce-client-app-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-common/jars/hadoop-mapreduce-client-common-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-yarn-common/jars/hadoop-yarn-common-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-yarn-api/jars/hadoop-yarn-api-2.2.0.jar:/root/.ivy2/cache/com.google.inject/guice/jars/guice-3.0.jar:/root/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/root/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:/root/.ivy2/cache/org.sonatype.sisu.inject/cglib/jars/cglib-2.2.1-v20090111.jar:/root/.ivy2/cache/asm/asm/jars/asm-3.2.jar:/root/.ivy2/cache/com.sun.jersey.jersey-test-framework/jersey-test-framework-grizzly2/jars/jersey-test-framework-grizzly2-1.9.jar:/root/.ivy2/cache/com.sun.jersey/jersey-server/bundles/jersey-server-1.9.jar:/root/.ivy2/cache/com.sun.jersey/jersey-json/bundles/jersey-json-1.9.jar:/root/.ivy2/cache/org.codehaus.jettison/jettison/bundles/jettison-1.1.jar:/root/.ivy2/cache/stax/stax-api/jars/stax-api-1.0.1.jar:/root/.ivy2/cache/com.sun.xml.bind/jaxb-impl/jars/jaxb-impl-2.2.3-1.jar:/root/.ivy2/cache/javax.xml.bind/jaxb-api/jars/jaxb-api-2.2.2.jar:/root/.ivy2/cache/javax.activation/activation/jars/activation-1.1.jar:/root/.ivy2/cache/org.codehaus.jackson/jackson-jaxrs/jars/jackson-jaxrs-1.8.8.jar:/root/.ivy2/cache/org.codehaus.jackson/jackson-xc/jars/jackson-xc-1.8.8.jar:/root/.ivy2/cache/com.sun.jersey.contribs/jersey-guice/jars/jersey-guice-1.9.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-yarn-client/jars/hadoop-yarn-client-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-core/jars/hadoop-mapreduce-client-core-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-yarn-server-common/jars/hadoop-yarn-server-common-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-shuffle/jars/hadoop-mapreduce-client-shuffle-2.2.0.jar:/root/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-jobclient/jars/hadoop-mapreduce-client-jobclient-2.2.0.jar:/root/.ivy2/cache/org.apache.spark/spark-network-common_2.10/jars/spark-network-common_2.10-1.3.0.jar:/root/.ivy2/cache/org.spark-project.spark/unused/jars/unused-1.0.0.jar:/root/.ivy2/cache/org.apache.spark/spark-network-shuffle_2.10/jars/spark-network-shuffle_2.10-1.3.0.jar:/root/.ivy2/cache/net.java.dev.jets3t/jets3t/jars/jets3t-0.7.1.jar:/root/.ivy2/cache/org.apache.curator/curator-recipes/bundles/curator-recipes-2.4.0.jar:/root/.ivy2/cache/org.apache.curator/curator-framework/bundles/curator-framework-2.4.0.jar:/root/.ivy2/cache/org.apache.curator/curator-client/bundles/curator-client-2.4.0.jar:/root/.ivy2/cache/org.apache.zookeeper/zookeeper/jars/zookeeper-3.4.5.jar:/root/.ivy2/cache/jline/jline/jars/jline-0.9.94.jar:/root/.ivy2/cache/com.google.guava/guava/bundles/guava-14.0.1.jar:/root/.ivy2/cache/org.eclipse.jetty.orbit/javax.servlet/orbits/javax.servlet-3.0.0.v201112011016.jar:/root/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.3.2.jar:/root/.ivy2/cache/org.apache.commons/commons-math3/jars/commons-math3-3.1.1.jar:/root/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.10.jar:/root/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.10.jar:/root/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.10.jar:/root/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.10.jar:/root/.ivy2/cache/com.ning/compress-lzf/bundles/compress-lzf-1.0.0.jar:/root/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.1.1.6.jar:/root/.ivy2/cache/net.jpountz.lz4/lz4/jars/lz4-1.2.0.jar:/root/.ivy2/cache/org.roaringbitmap/RoaringBitmap/bundles/RoaringBitmap-0.4.5.jar:/root/.ivy2/cache/commons-net/commons-net/jars/commons-net-2.2.jar:/root/.ivy2/cache/org.spark-project.akka/akka-remote_2.10/jars/akka-remote_2.10-2.3.4-spark.jar:/root/.ivy2/cache/org.spark-project.akka/akka-actor_2.10/jars/akka-actor_2.10-2.3.4-spark.jar:/root/.ivy2/cache/io.netty/netty/bundles/netty-3.8.0.Final.jar:/root/.ivy2/cache/org.spark-project.protobuf/protobuf-java/bundles/protobuf-java-2.5.0-spark.jar:/root/.ivy2/cache/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar:/root/.ivy2/cache/org.spark-project.akka/akka-slf4j_2.10/jars/akka-slf4j_2.10-2.3.4-spark.jar:/root/.ivy2/cache/org.json4s/json4s-jackson_2.10/jars/json4s-jackson_2.10-3.2.10.jar:/root/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.10.jar:/root/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.10.jar:/root/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar:/root/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.10.0.jar:/root/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.0.jar:/root/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.4.4.jar:/root/.ivy2/cache/org.apache.mesos/mesos/jars/mesos-0.21.0-shaded-protobuf.jar:/root/.ivy2/cache/com.clearspring.analytics/stream/jars/stream-2.7.0.jar:/root/.ivy2/cache/io.dropwizard.metrics/metrics-core/bundles/metrics-core-3.1.0.jar:/root/.ivy2/cache/io.dropwizard.metrics/metrics-jvm/bundles/metrics-jvm-3.1.0.jar:/root/.ivy2/cache/io.dropwizard.metrics/metrics-json/bundles/metrics-json-3.1.0.jar:/root/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.4.4.jar:/root/.ivy2/cache/io.dropwizard.metrics/metrics-graphite/bundles/metrics-graphite-3.1.0.jar:/root/.ivy2/cache/com.fasterxml.jackson.module/jackson-module-scala_2.10/bundles/jackson-module-scala_2.10-2.4.4.jar:/root/.sbt/boot/scala-2.10.4/lib/scala-reflect.jar:/root/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.4.4.jar:/root/.ivy2/cache/org.apache.ivy/ivy/jars/ivy-2.4.0.jar:/root/.ivy2/cache/oro/oro/jars/oro-2.0.8.jar:/root/.ivy2/cache/org.tachyonproject/tachyon-client/jars/tachyon-client-0.5.0.jar:/root/.ivy2/cache/org.tachyonproject/tachyon/jars/tachyon-0.5.0.jar:/root/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar:/root/.ivy2/cache/org.spark-project/pyrolite/jars/pyrolite-2.0.1.jar:/root/.ivy2/cache/net.sf.py4j/py4j/jars/py4j-0.8.2.1.jar spark.jobserver.JobServer /home/hadoop/yanchen/spark-jobserver/config/local.conf

**Comment by ChenYanting** [comment]
@velvia 
Are these information enough for you to detect where the error comes from?

**Comment by velvia** [comment]
@ChenYanting Hmm.  So it seems Akka version matches exactly.  However, one thing I noticed in your classpath is that it is including the development class files from job server:   eg /home/hadoop/yanchen/spark-jobserver/job-server-api/target/scala-2.10/classes.   I also don't see spark-job-server.jar in the classpath from Spark UI.   Would you mind making sure Spark is using the assembly jar?  There could be other jars missing due to that.

**Comment by ChenYanting** [comment]
@velvia 
I modify the local.conf under config folder. In the beginning, I let it point to a CDH's Spark cluster. The jobserver works well when submitting job to CDH's Spark Cluster through jobserver. However, when I install another Spark Cluster using binary file instead of CDH, the submission is failed. The error message above happens in my second Spark Cluster. 

As a result, I am not sure if the classpath is the real problem that cause my job submission failed. @@

**Comment by velvia** [comment]
Sorry what do u mean by binary file?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ChenYanting** [comment]
@velvia 

I found the problem!
In jobserver/project/Dependencies.scala
There is an variable called sparkVersion. The version must be the same as the Spark cluster that jobserver connects to.

CDH includes spark 1.3.0 
My another spark cluster uses 1.3.1
My Dependencies.scala uses 1.3.0

As a result, my jobserver is only able to talk with CDH spark cluster. After I modify the version, now it can talk to my another spark cluster!

**Comment by velvia** [comment]
Thanks!  Glad you figured it out.

On Wed, May 27, 2015 at 12:11 AM, Yanting Chen <notifications@github.com>
wrote:

> @velvia <https://github.com/velvia>
>
> I found the problem!
> In jobserver/project/Dependencies.scala
> There is an variable called sparkVersion. The version must be the same as
> the Spark cluster that jobserver connects to.
>
> CDH includes spark 1.3.0
> My another spark cluster uses 1.3.1
> My Dependencies.scala uses 1.3.0
>
> As a result, my jobserver is only able to talk with CDH spark cluster.
> After I modify the version, now it can talk to my another spark cluster!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/154#issuecomment-105788758>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Going to close.

**Comment by manasdebashiskar** [comment]
Hi @velvia  and @ChenYanting . From this discussion I got the impression that the master branch of Job server will run againt CDH5.4 if sparkVersion is changed to "1.3.0".
However I don't see that to be the case.
I see a stack trace that suggest the same error. 

###### java.lang.NoSuchMethodError: akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor######

I am assuming there were some changes since this discussion happened so I checked the tag v0.5.1 and still got the same error.

Am I missing any other step here?

Thanks
Manas

**Comment by velvia** [comment]
@ChenYanting are you able to help @manasdebashiskar ?

**Comment by manasdebashiskar** [comment]
Hi @ChenYanting do you or anyone you know have managed to get job server working with CDH5.4(containing spark 1.3.0)?
@velvia , the errors still look as if the Akka versions don't match. But the fact that @ChenYanting has got it working makes me wonder if actually I am missing some steps.

Appreciate the help.
..Manas

**Comment by velvia** [comment]
Manas, can you confirm what version of Akka CDH5.4 runs with?

On Fri, Jun 26, 2015 at 9:00 PM, manas <notifications@github.com> wrote:

> Hi @ChenYanting <https://github.com/ChenYanting> do you or anyone you
> know have managed to get job server working with CDH5.4(containing spark
> 1.3.0)?
> @velvia <https://github.com/velvia> , the errors still look as if the
> Akka versions don't match. But the fact that @ChenYanting
> <https://github.com/ChenYanting> has got it working makes me wonder if
> actually I am missing some steps.
>
> Appreciate the help.
> ..Manas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/154#issuecomment-115953620>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by manasdebashiskar** [comment]
Hi @velvia ,
 I am surprised and a little disappointed after finding the answer to your question.
CDH5.4 (https://github.com/cloudera/spark/blob/cdh5-1.3.0_5.4.2/pom.xml)
uses an older version of Akka still  **2.2.3-shaded-protobuf** which seems to be causing the problem.

*ps:Cloudera has said in several blogs that they have rebased spark with the master for 1.3 and onwards*

Do you have any suggestion for me how to enforce that version of akka in job server for the build?

Many Thanks
....Manas

**Comment by velvia** [comment]
Manas,

Modify Dependencies.scala, you will see two lines with Akka dependencies
that contain "2.3.4", such as

  "com.typesafe.akka" %% "akka-slf4j" % "2.3.4" % "provided",

Change the "2.3.4" to "2.2.3", and you should be fine.  We don't use
protobuf to serialize messages, so hopefully there shouldn't be conflicts.
Good luck!

On Sat, Jun 27, 2015 at 8:53 AM, manas <notifications@github.com> wrote:

> Hi @velvia <https://github.com/velvia> ,
> I am surprised and a little disappointed after finding the answer to your
> question.
> CDH5.4 (https://github.com/cloudera/spark/blob/cdh5-1.3.0_5.4.2/pom.xml)
> uses an older version of Akka still *2.2.3-shaded-protobuf* which seems
> to be causing the problem.
>
> *ps:Cloudera has said in several blogs that they have rebased spark with
> the master for 1.3 and onwards*
>
> Do you have any suggestion for me how to enforce that version of akka in
> job server for the build?
>
> Many Thanks
> ....Manas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/154#issuecomment-116091264>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by Dom-nik** [comment]
Excuse me if I'm ignorant, but how can I make use of Dependencies.scala file?
Is it used for building spark-job-server.jar ? Can you please instruct me on how to build it?

**Comment by velvia** [comment]
Yes, it’s part of building.  You can build the main jar file with “sbt job-server-extras/assembly”, or use one of the deploy scripts like “server_deploy.sh”.  See the Deploying section of the README.

**Comment by ramanKC** [comment]
Hi velvia,
I have modified Dependencies.scala, changed "2.3.4" to "2.2.3", but still the error persists.
I have CDH5.4 with Spark-1.3.0. I am using spark-jobserver-0.5.1.


Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor;
	at spray.routing.directives.DetachMagnet2LowerPriorityImplicits.fromImplicitRefFactory(ExecutionDirectives.scala:116)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:67)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:57)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:48)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:22)
	at ooyala.common.akka.web.CommonRoutes$class.$init$(CommonRoutes.scala:20)
	at spark.jobserver.WebApi.<init>(WebApi.scala:22)
	at spark.jobserver.JobServer$.start(JobServer.scala:58)
	at spark.jobserver.JobServer$.main(JobServer.scala:63)
	at spark.jobserver.JobServer.main(JobServer.scala)

**Comment by lizanle521** [comment]
now i'm using spark-jobserver-0.6.1-spark-1.5.0.  with spark.1.5.0-cdh5.5.5 . and i 'm so disapointment to find that this problem still exist. could anyone help me please ?

**Comment by velvia** [comment]
Unfortunately if you use CDH life will be a pain  :-p   
If you are able to use Spark 2.0, things should get much better, because that does not bundle Akka any more.
