### ISSUE TITLE
Job server does not work with spark built with scala 2.11

### ISSUE THREAD

**Issue by manasdebashiskar** [spark-jobserver/spark-jobserver#320]
Hi, 
 Job server does not cross compile with scala 2.10 and 2.11.
 My job server (V.1.5.1)
 My spark is built with scala 2.11.
When I try to run the job server it fails with the following error. 
These kind of errors typically mean there is a compatibility issue between the akka version(That is my guess. Feel free to prove me wrong.)

Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at spray.http.MediaTypes$.register(MediaType.scala:236)
	at spray.http.MediaTypes$.app(MediaType.scala:241)
	at spray.http.MediaTypes$.<init>(MediaType.scala:282)
	at spray.http.MediaTypes$.<clinit>(MediaType.scala)
	at spray.routing.directives.ContentTypeResolver$$anon$1.apply(FileAndResourceDirectives.scala:272)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:57)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:91)
	at spray.routing.directives.FileAndResourceDirectives$class.getFromFile(FileAndResourceDirectives.scala:48)
	at spark.jobserver.WebApi.getFromFile(WebApi.scala:91)
	at ooyala.common.akka.web.CommonRoutes$class.$init$(CommonRoutes.scala:20)
	at spark.jobserver.WebApi.<init>(WebApi.scala:98)
	at spark.jobserver.JobServer$.start(JobServer.scala:72)
	at spark.jobserver.JobServer$.main(JobServer.scala:121)
	at spark.jobserver.JobServer.main(JobServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Thanks
Manas

**Comment by velvia** [comment]
So your job server is built with Scala 2.11 is that right?
And what environment/distro is your Spark?

**Comment by velvia** [comment]
i.e. are you using CDH?

**Comment by zeitos** [comment]
If your spark was built with 2.11 you should build jobserver for 2.11 (just change the SCALA_VERSION in the config/local.sh)

**Comment by manasdebashiskar** [comment]
Hi,
My spark is 1.5.3 branch built with cdh5.4 hadoop2. 6
It is NOT the one that comes packaged with cloudera.
Yes my job server is built with 2.11 using the mechanism prescribed above.
I. E. Change scala version in local. Sh. I will give it one more try
tomorrow to eliminate the possibility of having built the spark incorrectly.
In the mean time any suggestion to streer my analysis is welcome.

**Comment by zeitos** [comment]
any news @manasdebashiskar  ? I've no idea which scala version CDH uses for spark :S 
( I use vanilla hadoop 2.6 & spark built with 2.11 by me and it works great )

**Comment by manasdebashiskar** [comment]
I have to do more thorough tests to find the root cause of the problem @zeitos.
