### ISSUE TITLE
Run on spark1.4.1 java.lang.NoSuchMethodError: org.joda.time.DateTime.now

### ISSUE THREAD

**Issue by cookeem** [spark-jobserver/spark-jobserver#280]
I run SJS in deploy mode with spark1.4.1, when I send the WordCountExample to the SJS

curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests-$VER.jar localhost:8090/jars/test

the SJS down immediately(run in sbt develop mode is fine), it said that NoSuchMethodError: org.joda.time.DateTime.now(), and I can see this method in spark-job-server.jar. Spark version 1.4.1+ Scala 2.11.6, I use scala shell and add joda-time-2.5.jar then input org.joda.time.DateTime.now(), output is fine, but when I use spark shell then input org.joda.time.DateTime.now(), output like this:

<console>:21: error: value now is not a member of object org.joda.time.DateTime
              org.joda.time.DateTime.now()

SJS output log like this,so confuse about it:

[2015-10-10 11:19:58,926] ERROR akka.actor.ActorSystemImpl [] [ActorSystem(JobServer)] - Uncaught error from thread [JobServer-akka.actor.default-dispatcher-9] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime;
	at spark.jobserver.JarManager.spark$jobserver$JarManager$$saveJar(JarManager.scala:33)
	at spark.jobserver.JarManager$$anonfun$wrappedReceive$1.applyOrElse(JarManager.scala:67)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2015-10-10 11:19:58,938] INFO  rg.apache.spark.util.Utils [] [] - Shutdown hook called

**Comment by velvia** [comment]
Are you running a standard JDK?   Joda time APIs have not changed much, the now() method is pretty much in every version.  Very weird.

**Comment by cookeem** [comment]
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

spark version 1.4.1

I use scala shell 2.11.6 run org.joda.time.DateTime.now() is OK, but spark-shell 1.4.1 build with scala2.11.6 run org.joda.time.DateTime.now() will show NoSuchMethodError, too weird.

**Comment by velvia** [comment]
Have you tried downloading a pre-built Spark distribution?

You can try using the spark observer Docker container, which comes with a Spark distro.

**Comment by cookeem** [comment]
Hi velvia, finally I find the reason, spark1.4.1 pre-built version can not support org.joda.time.DateTime.now even I add joda-time-2.5.jar in the classpath (I don't know why actually), but I found solution by google, it is nscala-time.

I add library dependencies: "com.github.nscala-time" % "nscala-time_2.10" % "2.2.0", and replace all source code "import org.joda.time.DateTime" into "import com.github.nscala_time.time.Imports._", so that spark would not output "java.lang.NoSuchMethodError: org.joda.time.DateTime.now()" and now it work!

**Comment by Dom-nik** [comment]
I've just encountered the same error when running the tool with Spark 1.6.0 distributed with Cloudera Hadoop. I can't rebuild Spark, as it's prepackaged in CDH and maintained by another team.

Dou you have any suggestions?

**Comment by koettert** [comment]
Hi,
This time the problem is caused by incompatible class versions of the joda.time package in Hive and the Spark Job Server on Cloudera (java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime exception in the spark job server log). To solve the problem execute the following two commands on the machine the Job Server is installed:
```
 sed -i -e 's#--driver-class-path.*SPARK_HOME/../hive/lib/.*##' /opt/spark-job-server/manager_start.sh
sed -i -e 's#--driver-class-path.*SPARK_HOME/../hive/lib/.*##' /opt/spark-job-server/server_start.sh  
```
This removes the problematic driver class path entries from the two spark job server scripts.
Bye
Tobias

**Comment by Dom-nik** [comment]
Thanks Tobias, this worked!

**Comment by velvia** [comment]
Thanks Tobias.  Just added your advice to the troubleshooting page.

**Comment by WeizeSun** [comment]
Hey,
I am a newbie to sed and SJS, does the command means to remove all the "--driver-class-path.*SPARK_HOME/../hive/lib/.*" like sentences from the script manager_start.sh and server_start.sh? However I cannot find any sentence like it in those two scripts... And it does not change anything if I run sed -i -e 's#--driver-class-path.*SPARK_HOME/../hive/lib/.*##' to the scripts. Can you explain further?

I'd appreciate your help.
