### ISSUE TITLE
2.0-preview version doesn't work with spark 2.1.0 because of the shapeless version

### ISSUE THREAD

**Issue by txuwh** [spark-jobserver/spark-jobserver#724]
Hay everybody, 

I've tried to build the 2.0-preview with the latest spark 2.1.0 after modifying the versions of the dependencies in project directory. 

The build was OK. But the server can not start perhaps because of the conflict of shapeless version. 

The spark 2.1.0 uses shapeless 2.0.0 which conflicts with the spray in SJS.
I've tried a few different spray versions but the problem didn't go away. 

The error log is: 

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Exception in thread "main" java.lang.NoClassDefFoundError: shapeless/PrependAux$
        at spray.routing.directives.PathDirectives$class.pathPrefix(PathDirectives.scala:40)
        at spark.jobserver.WebApi.pathPrefix(WebApi.scala:113)
        at spray.routing.directives.PathDirectives$class.path(PathDirectives.scala:33)
        at spark.jobserver.WebApi.path(WebApi.scala:113)
        at spark.jobserver.common.akka.web.CommonRoutes$class.$init$(CommonRoutes.scala:15)
        at spark.jobserver.WebApi.<init>(WebApi.scala:120)
        at spark.jobserver.JobServer$.start(JobServer.scala:85)
        at spark.jobserver.JobServer$.main(JobServer.scala:156)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: shapeless.PrependAux$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by maxosprojects** [comment]
#699

**Comment by hntd187** [comment]
Please if we can follow the issue in #699
